### ISSUE TITLE
Migrate to Python 3

### ISSUE THREAD

**Issue by aelmahmoudy** [ojuba-org/hijra#2]
Python 2 end-of-life date is on 2020: http://legacy.python.org/dev/peps/pep-0373/

please migrate hijra to Python3.

**Comment by aelmahmoudy** [comment]
I got the following error after my attempt to migrate hijra to python3 (see python3 branch):

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/HijriCal.py", line 57, in goto_gregorian_day
    try: Y, M, D = gregorian_to_hijri(yy,mm,dd); self.goto_hijri_day(Y, M, D)
  File "/usr/lib/python3/dist-packages/hijra.py", line 201, in gregorian_to_hijri
    return absolute_to_hijri( gregorian_to_absolute (year, month, day));
  File "/usr/lib/python3/dist-packages/hijra.py", line 172, in absolute_to_hijri
    d=hijri_to_absolute(Y,M,1) # TODO: this is an expensive call
  File "/usr/lib/python3/dist-packages/hijra.py", line 127, in hijri_to_absolute
    for i in range(1,y): dc+=hijri_year_days(i)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/HijriApplet", line 49, in <module>
    cal = HijriCal()
  File "/usr/lib/python3/dist-packages/HijriCal.py", line 36, in __init__
    self.goto_today()
  File "/usr/lib/python3/dist-packages/HijriCal.py", line 42, in goto_today
    Y,M,D=self.goto_gregorian_day(yy, mm, dd)
  File "/usr/lib/python3/dist-packages/HijriCal.py", line 58, in goto_gregorian_day
    except: self.validate()
  File "/usr/lib/python3/dist-packages/HijriCal.py", line 93, in validate
    if self.M<1: self.M=12; self.Y-=1; f=1
AttributeError: 'HijriCal' object has no attribute 'M'
```

**Comment by aelmahmoudy** [comment]
Fixed in last commit to python3 branch
